name: Deploy Router to Cloud Run

on:
  workflow_dispatch:
  workflow_call:

env:
  GEN: ""

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - id: "auth"
      uses: "google-github-actions/auth@v0"
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    #- name: Set up Google Cloud SDK
    #  uses: google-github-actions/setup-gcloud@v0

    - name: Create Secret for Cloud Run
      run: gcloud secrets create ${{vars.ACTOR}}
      continue-on-error: true

    - name: Add Secret data
      run: gcloud secrets versions add --data-file=./router/router.yaml ${{vars.ACTOR}}

    - name: Depoy Apollo Router to Cloud Run
      run: |
        gcloud run deploy ${{vars.ACTOR}}-${{vars.WORKSHOPID}}-router --image gcr.io/summit-enterprise-workshop/jesse-apollo-router:latest \
          --command=/dist/router \
          --set-secrets=/dist/config/router.yaml=${{vars.ACTOR}}:latest \
          --set-env-vars "APOLLO_ROUTER_HOT_RELOAD=true,APOLLO_KEY=${{ vars.TOKEN }},APOLLO_GRAPH_REF=${{vars.ACTOR}}-${{vars.WORKSHOPID}}${{env.GEN}}@current" --platform managed --region us-central1 \
          --allow-unauthenticated

    - name: Deploy contract router to Cloud Run
      run: |
        gcloud run deploy ${{vars.ACTOR}}-${{vars.WORKSHOPID}}-contractrouter --image gcr.io/summit-enterprise-workshop/jesse-apollo-router:latest \
        --command=/dist/router \
        --set-secrets=/dist/config/router.yaml=${{vars.ACTOR}}:latest \
        --set-env-vars "APOLLO_ROUTER_HOT_RELOAD=true,APOLLO_KEY=${{ vars.TOKEN }},APOLLO_GRAPH_REF=${{vars.ACTOR}}-${{vars.WORKSHOPID}}${{env.GEN}}@Public" --platform managed --region us-central1 \
        --allow-unauthenticated
