name: Update Router on Cloud Run

on:
  push:
    paths:
      - '**.yaml'
  workflow_dispatch:
  workflow_call:

env:
  GEN: ""

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: "auth"
      uses: "google-github-actions/auth@v0"
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Add Secret data
      run: gcloud secrets versions add --data-file=./router/router.yaml ${{vars.ACTOR}}
